"""add dedup fields and owner_key

Revision ID: 4964b4761fe9
Revises: ed866b50b7f2
Create Date: 2026-07-09 10:31:56.267165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4964b4761fe9'
down_revision: Union[str, None] = 'ed866b50b7f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_imports', sa.Column('owner_key', sa.String(length=320), nullable=True))
    op.create_index(op.f('ix_lead_imports_owner_key'), 'lead_imports', ['owner_key'], unique=False)
    # Backfill existing rows via a server-side default, then drop it so the schema matches
    # the model (Python-side default only).
    op.add_column(
        'leads',
        sa.Column('is_duplicate', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('leads', 'is_duplicate', server_default=None)
    op.add_column('leads', sa.Column('duplicate_reason', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'duplicate_reason')
    op.drop_column('leads', 'is_duplicate')
    op.drop_index(op.f('ix_lead_imports_owner_key'), table_name='lead_imports')
    op.drop_column('lead_imports', 'owner_key')
    # ### end Alembic commands ###
