"""superadmin_null_org_scope

Revision ID: 6ffe5f5d541b
Revises: fdfda2294620
Create Date: 2026-07-20 18:21:25.403552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6ffe5f5d541b'
down_revision: Union[str, None] = 'fdfda2294620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uq_company_org_domain', 'companies', type_='unique')
    op.create_unique_constraint('uq_company_org_domain', 'companies', ['organization_id', 'domain'], postgresql_nulls_not_distinct=True)
    op.alter_column('crm_connections', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uq_crm_org_provider', 'crm_connections', type_='unique')
    op.create_unique_constraint('uq_crm_org_provider', 'crm_connections', ['organization_id', 'provider'], postgresql_nulls_not_distinct=True)
    op.alter_column('website_analyses', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uq_analysis_org_domain', 'website_analyses', type_='unique')
    op.create_unique_constraint('uq_analysis_org_domain', 'website_analyses', ['organization_id', 'domain'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_analysis_org_domain', 'website_analyses', type_='unique')
    op.create_unique_constraint('uq_analysis_org_domain', 'website_analyses', ['organization_id', 'domain'])
    op.alter_column('website_analyses', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('uq_crm_org_provider', 'crm_connections', type_='unique')
    op.create_unique_constraint('uq_crm_org_provider', 'crm_connections', ['organization_id', 'provider'])
    op.alter_column('crm_connections', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('uq_company_org_domain', 'companies', type_='unique')
    op.create_unique_constraint('uq_company_org_domain', 'companies', ['organization_id', 'domain'])
    op.alter_column('companies', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
