"""initial

Revision ID: ed866b50b7f2
Revises: 
Create Date: 2026-07-08 23:13:01.342193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ed866b50b7f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('SALESFORCE', 'HUBSPOT', 'ZOHO', 'DYNAMICS', 'PIPEDRIVE', name='crm_provider'), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider')
    )
    op.create_table('website_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VALIDATING', 'SCRAPING', 'EXTRACTING', 'GENERATING_INTELLIGENCE', 'COMPLETED', 'FAILED', name='analysis_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('page_title', sa.String(length=512), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('extracted_content', sa.Text(), nullable=True),
    sa.Column('crawled_pages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('used_playwright', sa.Boolean(), nullable=False),
    sa.Column('scrape_engine', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_analyses_domain'), 'website_analyses', ['domain'], unique=True)
    op.create_table('company_intelligences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_analysis_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('sub_industries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('business_model', sa.String(length=255), nullable=True),
    sa.Column('geography', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('company_size', sa.String(length=100), nullable=True),
    sa.Column('technology_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('business_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('value_propositions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_customers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('ai_cached', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['website_analysis_id'], ['website_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_intelligences_website_analysis_id'), 'company_intelligences', ['website_analysis_id'], unique=True)
    op.create_table('icps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_intelligence_id', sa.Integer(), nullable=False),
    sa.Column('campaign_objective', sa.Text(), nullable=True),
    sa.Column('target_industries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('company_size_ranges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_seniorities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_geographies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outreach_tone', sa.String(length=50), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_intelligence_id'], ['company_intelligences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icps_company_intelligence_id'), 'icps', ['company_intelligence_id'], unique=False)
    op.create_table('lead_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icp_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('MAPPING', 'IMPORTED', 'QUALIFYING', 'QUALIFIED', 'SCORING', 'SCORED', 'FAILED', name='import_status'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('raw_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_rows', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['icp_id'], ['icps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_imports_icp_id'), 'lead_imports', ['icp_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_import_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('employee_range', sa.String(length=100), nullable=True),
    sa.Column('annual_revenue', sa.String(length=100), nullable=True),
    sa.Column('revenue_range', sa.String(length=100), nullable=True),
    sa.Column('founded', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=2048), nullable=True),
    sa.Column('qualification_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'REVIEW', name='qualification_status'), nullable=False),
    sa.Column('qualification_checks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('qualification_override', sa.Boolean(), nullable=False),
    sa.Column('enrichment_content', sa.Text(), nullable=True),
    sa.Column('enriched_at_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_import_id'], ['lead_imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=False)
    op.create_index(op.f('ix_companies_lead_import_id'), 'companies', ['lead_import_id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_import_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('seniority', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=512), nullable=True),
    sa.Column('email_validation', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('linkedin_url', sa.String(length=2048), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('time_in_role', sa.String(length=100), nullable=True),
    sa.Column('time_at_company', sa.String(length=100), nullable=True),
    sa.Column('industry_score', sa.Float(), nullable=True),
    sa.Column('role_score', sa.Float(), nullable=True),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('tier', sa.Enum('HOT', 'WARM', 'NURTURE', 'DEPRIORITIZED', name='lead_tier'), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_import_id'], ['lead_imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_company_id'), 'leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_lead_import_id'), 'leads', ['lead_import_id'], unique=False)
    op.create_table('email_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'READY', 'FAILED', name='draft_status'), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('personalization_notes', sa.Text(), nullable=True),
    sa.Column('booking_link', sa.String(length=2048), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('ai_cached', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_drafts_lead_id'), 'email_drafts', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_drafts_lead_id'), table_name='email_drafts')
    op.drop_table('email_drafts')
    op.drop_index(op.f('ix_leads_lead_import_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_lead_import_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_lead_imports_icp_id'), table_name='lead_imports')
    op.drop_table('lead_imports')
    op.drop_index(op.f('ix_icps_company_intelligence_id'), table_name='icps')
    op.drop_table('icps')
    op.drop_index(op.f('ix_company_intelligences_website_analysis_id'), table_name='company_intelligences')
    op.drop_table('company_intelligences')
    op.drop_index(op.f('ix_website_analyses_domain'), table_name='website_analyses')
    op.drop_table('website_analyses')
    op.drop_table('crm_connections')
    # ### end Alembic commands ###
