"""v2_schema_initial

Revision ID: fdfda2294620
Revises: 
Create Date: 2026-07-20 17:32:22.838699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fdfda2294620'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_field_vectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_field', sa.String(length=100), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model', 'text', name='uq_canonical_vector_model_text')
    )
    op.create_index(op.f('ix_canonical_field_vectors_canonical_field'), 'canonical_field_vectors', ['canonical_field'], unique=False)
    op.create_table('global_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('enrichment_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enrichment_content', sa.Text(), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_till', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_companies_domain'), 'global_companies', ['domain'], unique=True)
    op.create_table('header_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normalized_header', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model', 'normalized_header', name='uq_header_embedding_model_text')
    )
    op.create_index(op.f('ix_header_embeddings_normalized_header'), 'header_embeddings', ['normalized_header'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tenants_public_id'), 'tenants', ['public_id'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_org_tenant_name')
    )
    op.create_index(op.f('ix_organizations_public_id'), 'organizations', ['public_id'], unique=True)
    op.create_index(op.f('ix_organizations_tenant_id'), 'organizations', ['tenant_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('employee_range', sa.String(length=100), nullable=True),
    sa.Column('annual_revenue', sa.String(length=100), nullable=True),
    sa.Column('revenue_range', sa.String(length=100), nullable=True),
    sa.Column('founded', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=2048), nullable=True),
    sa.Column('enrichment_content', sa.Text(), nullable=True),
    sa.Column('enrichment_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enriched_at_status', sa.String(length=50), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrichment_valid_till', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'domain', name='uq_company_org_domain')
    )
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_organization_id'), 'companies', ['organization_id'], unique=False)
    op.create_index(op.f('ix_companies_public_id'), 'companies', ['public_id'], unique=True)
    op.create_table('crm_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('SALESFORCE', 'HUBSPOT', 'ZOHO', 'DYNAMICS', 'PIPEDRIVE', name='crm_provider'), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'provider', name='uq_crm_org_provider')
    )
    op.create_index(op.f('ix_crm_connections_organization_id'), 'crm_connections', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=512), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'USER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role = 'SUPER_ADMIN' OR organization_id IS NOT NULL", name='ck_users_org_required_unless_superadmin'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_table('website_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VALIDATING', 'SCRAPING', 'EXTRACTING', 'GENERATING_INTELLIGENCE', 'COMPLETED', 'FAILED', name='analysis_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('page_title', sa.String(length=512), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('extracted_content', sa.Text(), nullable=True),
    sa.Column('crawled_pages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('used_playwright', sa.Boolean(), nullable=False),
    sa.Column('scrape_engine', sa.String(length=50), nullable=True),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'domain', name='uq_analysis_org_domain')
    )
    op.create_index(op.f('ix_website_analyses_domain'), 'website_analyses', ['domain'], unique=False)
    op.create_index(op.f('ix_website_analyses_organization_id'), 'website_analyses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_website_analyses_public_id'), 'website_analyses', ['public_id'], unique=True)
    op.create_table('calcom_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calcom_user_email', sa.String(length=320), nullable=True),
    sa.Column('calcom_username', sa.String(length=255), nullable=True),
    sa.Column('encrypted_access_token', sa.Text(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', sa.String(length=512), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('selected_event_type_id', sa.Integer(), nullable=True),
    sa.Column('selected_event_type_slug', sa.String(length=255), nullable=True),
    sa.Column('selected_event_type_title', sa.String(length=255), nullable=True),
    sa.Column('working_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('working_hours_start', sa.String(length=5), nullable=False),
    sa.Column('working_hours_end', sa.String(length=5), nullable=False),
    sa.Column('calcom_schedule_id', sa.Integer(), nullable=True),
    sa.Column('calcom_schedule_name', sa.String(length=255), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.String(length=1024), nullable=True),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calcom_connections_public_id'), 'calcom_connections', ['public_id'], unique=True)
    op.create_index(op.f('ix_calcom_connections_user_id'), 'calcom_connections', ['user_id'], unique=True)
    op.create_table('company_intelligences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_analysis_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('sub_industries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('business_model', sa.String(length=255), nullable=True),
    sa.Column('geography', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('company_size', sa.String(length=100), nullable=True),
    sa.Column('technology_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('business_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('value_propositions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_customers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('ai_cached', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['website_analysis_id'], ['website_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_intelligences_public_id'), 'company_intelligences', ['public_id'], unique=True)
    op.create_index(op.f('ix_company_intelligences_website_analysis_id'), 'company_intelligences', ['website_analysis_id'], unique=True)
    op.create_table('mailbox_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', 'MICROSOFT', name='mailbox_provider'), nullable=False),
    sa.Column('email_address', sa.String(length=320), nullable=False),
    sa.Column('imap_host', sa.String(length=255), nullable=False),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('encrypted_app_password', sa.Text(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('last_verification_error', sa.String(length=1024), nullable=True),
    sa.Column('imap_uidvalidity', sa.Integer(), nullable=True),
    sa.Column('last_polled_uid', sa.Integer(), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'email_address', name='uq_mailbox_user_email')
    )
    op.create_index(op.f('ix_mailbox_connections_public_id'), 'mailbox_connections', ['public_id'], unique=True)
    op.create_index(op.f('ix_mailbox_connections_user_id'), 'mailbox_connections', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='campaign_status'), nullable=False),
    sa.Column('website_analysis_id', sa.Integer(), nullable=True),
    sa.Column('company_intelligence_id', sa.Integer(), nullable=True),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_intelligence_id'], ['company_intelligences.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_analysis_id'], ['website_analyses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_public_id'), 'campaigns', ['public_id'], unique=True)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_campaigns_user_id'), 'campaigns', ['user_id'], unique=False)
    op.create_table('icps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('company_intelligence_id', sa.Integer(), nullable=True),
    sa.Column('campaign_objective', sa.Text(), nullable=True),
    sa.Column('campaign_objective_options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_industries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('company_size_ranges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_seniorities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_geographies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outreach_tone', sa.String(length=50), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_intelligence_id'], ['company_intelligences.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'version', name='uq_icp_campaign_version')
    )
    op.create_index(op.f('ix_icps_campaign_id'), 'icps', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_icps_company_intelligence_id'), 'icps', ['company_intelligence_id'], unique=False)
    op.create_index(op.f('ix_icps_public_id'), 'icps', ['public_id'], unique=True)
    op.create_index('ux_icps_campaign_active', 'icps', ['campaign_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('lead_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('PRIMARY', 'PENDING_REUPLOAD', name='import_kind'), nullable=False),
    sa.Column('icp_snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('MAPPING', 'IMPORTED', 'QUALIFYING', 'QUALIFIED', 'SCORING', 'SCORED', 'FAILED', name='import_status'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('raw_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mapping_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('enrichment_total', sa.Integer(), nullable=True),
    sa.Column('enrichment_done', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_imports_campaign_id'), 'lead_imports', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_lead_imports_public_id'), 'lead_imports', ['public_id'], unique=True)
    op.create_index('ux_lead_imports_campaign_primary', 'lead_imports', ['campaign_id'], unique=True, postgresql_where=sa.text("kind = 'PRIMARY'"))
    op.create_table('company_qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_import_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('qualification_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'REVIEW', name='qualification_status'), nullable=False),
    sa.Column('qualification_checks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('qualification_override', sa.Boolean(), nullable=False),
    sa.Column('industry_match_score', sa.Float(), nullable=True),
    sa.Column('company_fit_score', sa.Float(), nullable=True),
    sa.Column('qualification_reasoning', sa.Text(), nullable=True),
    sa.Column('solvable_pain_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_import_id'], ['lead_imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_import_id', 'company_id', name='uq_company_qualification_import_company')
    )
    op.create_index(op.f('ix_company_qualifications_company_id'), 'company_qualifications', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_qualifications_lead_import_id'), 'company_qualifications', ['lead_import_id'], unique=False)
    op.create_table('lead_import_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_import_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_import_id'], ['lead_imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_import_id', 'row_number', name='uq_import_row_number')
    )
    op.create_index(op.f('ix_lead_import_rows_lead_import_id'), 'lead_import_rows', ['lead_import_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_import_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('seniority', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=512), nullable=True),
    sa.Column('email_validation', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('linkedin_url', sa.String(length=2048), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('time_in_role', sa.String(length=100), nullable=True),
    sa.Column('time_at_company', sa.String(length=100), nullable=True),
    sa.Column('years_experience', sa.String(length=100), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_reason', sa.String(length=512), nullable=True),
    sa.Column('outreach_paused', sa.Boolean(), nullable=False),
    sa.Column('role_score', sa.Float(), nullable=True),
    sa.Column('signal_score', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('tier', sa.Enum('HOT', 'WARM', 'NURTURE', 'DEPRIORITIZED', name='lead_tier'), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_import_id'], ['lead_imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_company_id'), 'leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_lead_import_id'), 'leads', ['lead_import_id'], unique=False)
    op.create_index(op.f('ix_leads_public_id'), 'leads', ['public_id'], unique=True)
    op.create_index('ux_leads_import_email', 'leads', ['lead_import_id', sa.text('lower(email)')], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_table('email_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'LINKEDIN', 'CALL', name='draft_channel'), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'READY', 'FAILED', 'SENT', 'APPROVED', 'SCHEDULED', 'SENDING', 'NEEDS_ATTENTION', name='draft_status'), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('personalization_notes', sa.Text(), nullable=True),
    sa.Column('booking_link', sa.String(length=2048), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('ai_cached', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_test_email', sa.String(length=320), nullable=True),
    sa.Column('last_test_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refine_count', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=512), nullable=True),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheduled_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_drafts_lead_id'), 'email_drafts', ['lead_id'], unique=False)
    op.create_index(op.f('ix_email_drafts_public_id'), 'email_drafts', ['public_id'], unique=True)
    op.create_index('ux_email_drafts_lead_step', 'email_drafts', ['lead_id', 'channel', 'step_index'], unique=True, postgresql_where=sa.text('step_index < 100'))
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('due_step_index', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_lead_id'), 'notifications', ['lead_id'], unique=False)
    op.create_index(op.f('ix_notifications_public_id'), 'notifications', ['public_id'], unique=True)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('dispatch_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.String(length=1024), nullable=True),
    sa.Column('message_id', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['email_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_logs_draft_id'), 'dispatch_logs', ['draft_id'], unique=False)
    op.create_table('inbound_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailbox_connection_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('matched_draft_id', sa.Integer(), nullable=True),
    sa.Column('imap_uid', sa.Integer(), nullable=False),
    sa.Column('imap_message_id', sa.String(length=998), nullable=False),
    sa.Column('in_reply_to', sa.String(length=998), nullable=True),
    sa.Column('from_address', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.String(length=998), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intent', sa.Enum('NEGATIVE', 'NEUTRAL', 'POSITIVE', 'BOOKED', name='reply_intent'), nullable=True),
    sa.Column('intent_confidence', sa.Float(), nullable=True),
    sa.Column('intent_reason', sa.String(length=1024), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.String(length=1024), nullable=True),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mailbox_connection_id'], ['mailbox_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_draft_id'], ['email_drafts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mailbox_connection_id', 'imap_message_id', name='uq_inbound_reply_mailbox_message')
    )
    op.create_index(op.f('ix_inbound_replies_lead_id'), 'inbound_replies', ['lead_id'], unique=False)
    op.create_index(op.f('ix_inbound_replies_mailbox_connection_id'), 'inbound_replies', ['mailbox_connection_id'], unique=False)
    op.create_index(op.f('ix_inbound_replies_public_id'), 'inbound_replies', ['public_id'], unique=True)
    op.create_table('pending_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('inbound_reply_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'NEEDS_REVIEW', 'BOOKING', 'AWAITING_RESLOT', 'BOOKED', 'CANCELLED', name='pending_booking_status'), nullable=False),
    sa.Column('resolved_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_timezone', sa.String(length=64), nullable=True),
    sa.Column('timezone_source', sa.Enum('EXPLICIT', 'LEAD_COUNTRY', 'UNKNOWN', name='timezone_source'), nullable=True),
    sa.Column('raw_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calcom_booking_uid', sa.String(length=255), nullable=True),
    sa.Column('meeting_url', sa.String(length=2048), nullable=True),
    sa.Column('last_error', sa.String(length=1024), nullable=True),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inbound_reply_id'], ['inbound_replies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_bookings_inbound_reply_id'), 'pending_bookings', ['inbound_reply_id'], unique=False)
    op.create_index(op.f('ix_pending_bookings_lead_id'), 'pending_bookings', ['lead_id'], unique=False)
    op.create_index(op.f('ix_pending_bookings_public_id'), 'pending_bookings', ['public_id'], unique=True)
    op.create_index(op.f('ix_pending_bookings_user_id'), 'pending_bookings', ['user_id'], unique=False)
    op.create_index('ux_pending_bookings_reply_live', 'pending_bookings', ['inbound_reply_id'], unique=True, postgresql_where=sa.text("status != 'CANCELLED'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_pending_bookings_reply_live', table_name='pending_bookings', postgresql_where=sa.text("status != 'CANCELLED'"))
    op.drop_index(op.f('ix_pending_bookings_user_id'), table_name='pending_bookings')
    op.drop_index(op.f('ix_pending_bookings_public_id'), table_name='pending_bookings')
    op.drop_index(op.f('ix_pending_bookings_lead_id'), table_name='pending_bookings')
    op.drop_index(op.f('ix_pending_bookings_inbound_reply_id'), table_name='pending_bookings')
    op.drop_table('pending_bookings')
    op.drop_index(op.f('ix_inbound_replies_public_id'), table_name='inbound_replies')
    op.drop_index(op.f('ix_inbound_replies_mailbox_connection_id'), table_name='inbound_replies')
    op.drop_index(op.f('ix_inbound_replies_lead_id'), table_name='inbound_replies')
    op.drop_table('inbound_replies')
    op.drop_index(op.f('ix_dispatch_logs_draft_id'), table_name='dispatch_logs')
    op.drop_table('dispatch_logs')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_public_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_lead_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ux_email_drafts_lead_step', table_name='email_drafts', postgresql_where=sa.text('step_index < 100'))
    op.drop_index(op.f('ix_email_drafts_public_id'), table_name='email_drafts')
    op.drop_index(op.f('ix_email_drafts_lead_id'), table_name='email_drafts')
    op.drop_table('email_drafts')
    op.drop_index('ux_leads_import_email', table_name='leads', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_index(op.f('ix_leads_public_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_import_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_lead_import_rows_lead_import_id'), table_name='lead_import_rows')
    op.drop_table('lead_import_rows')
    op.drop_index(op.f('ix_company_qualifications_lead_import_id'), table_name='company_qualifications')
    op.drop_index(op.f('ix_company_qualifications_company_id'), table_name='company_qualifications')
    op.drop_table('company_qualifications')
    op.drop_index('ux_lead_imports_campaign_primary', table_name='lead_imports', postgresql_where=sa.text("kind = 'PRIMARY'"))
    op.drop_index(op.f('ix_lead_imports_public_id'), table_name='lead_imports')
    op.drop_index(op.f('ix_lead_imports_campaign_id'), table_name='lead_imports')
    op.drop_table('lead_imports')
    op.drop_index('ux_icps_campaign_active', table_name='icps', postgresql_where=sa.text('is_active'))
    op.drop_index(op.f('ix_icps_public_id'), table_name='icps')
    op.drop_index(op.f('ix_icps_company_intelligence_id'), table_name='icps')
    op.drop_index(op.f('ix_icps_campaign_id'), table_name='icps')
    op.drop_table('icps')
    op.drop_index(op.f('ix_campaigns_user_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_public_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_mailbox_connections_user_id'), table_name='mailbox_connections')
    op.drop_index(op.f('ix_mailbox_connections_public_id'), table_name='mailbox_connections')
    op.drop_table('mailbox_connections')
    op.drop_index(op.f('ix_company_intelligences_website_analysis_id'), table_name='company_intelligences')
    op.drop_index(op.f('ix_company_intelligences_public_id'), table_name='company_intelligences')
    op.drop_table('company_intelligences')
    op.drop_index(op.f('ix_calcom_connections_user_id'), table_name='calcom_connections')
    op.drop_index(op.f('ix_calcom_connections_public_id'), table_name='calcom_connections')
    op.drop_table('calcom_connections')
    op.drop_index(op.f('ix_website_analyses_public_id'), table_name='website_analyses')
    op.drop_index(op.f('ix_website_analyses_organization_id'), table_name='website_analyses')
    op.drop_index(op.f('ix_website_analyses_domain'), table_name='website_analyses')
    op.drop_table('website_analyses')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_crm_connections_organization_id'), table_name='crm_connections')
    op.drop_table('crm_connections')
    op.drop_index(op.f('ix_companies_public_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_organization_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_organizations_tenant_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_public_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_tenants_public_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_header_embeddings_normalized_header'), table_name='header_embeddings')
    op.drop_table('header_embeddings')
    op.drop_index(op.f('ix_global_companies_domain'), table_name='global_companies')
    op.drop_table('global_companies')
    op.drop_index(op.f('ix_canonical_field_vectors_canonical_field'), table_name='canonical_field_vectors')
    op.drop_table('canonical_field_vectors')
    # ### end Alembic commands ###
