import enum
from datetime import datetime

from sqlalchemy import DateTime, Enum, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, PublicIDMixin, TimestampMixin


REFINE_LIMIT = 2  # max Regenerate/Shorter/More Technical/.../Personalize Further calls per draft


class DraftChannel(str, enum.Enum):
    EMAIL = "email"
    LINKEDIN = "linkedin"
    CALL = "call"


# Fixed step positions in the per-lead sequence. The initial email is autogenerated
# (existing flow, untouched); everything after it is generated on user click.
STEP_INITIAL = 1
STEP_FOLLOW_UP_FIRST = 2  # follow-ups occupy 2, 3, 4
STEP_FOLLOW_UP_LAST = 4
STEP_LINKEDIN = 5
STEP_CALL = 6

# Days after the previous email's dispatch at which the follow-up-due notification
# fires, keyed by the follow-up's step_index: FU1 3d after initial, FU2 4d after FU1,
# FU3 7d after FU2.
FOLLOW_UP_DUE_DAYS = {2: 3, 3: 4, 4: 7}


class DraftStatus(str, enum.Enum):
    PENDING = "pending"
    GENERATING = "generating"
    READY = "ready"
    FAILED = "failed"
    SENT = "sent"
    APPROVED = "approved"
    # Dispatch lifecycle (see scheduling_service): SCHEDULED holds a future slot;
    # SENDING is the transient claim taken just before SMTP so a crash mid-send can
    # never be silently re-dispatched; NEEDS_ATTENTION marks a dispatch interrupted
    # mid-send (outcome unknown — user must verify their Sent folder and resolve).
    SCHEDULED = "scheduled"
    SENDING = "sending"
    NEEDS_ATTENTION = "needs_attention"


class EmailDraft(Base, PublicIDMixin, TimestampMixin):
    __tablename__ = "email_drafts"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    lead_id: Mapped[int] = mapped_column(ForeignKey("leads.id", ondelete="CASCADE"), nullable=False, index=True)

    # Position in the lead's outreach sequence (see STEP_* constants). channel decides
    # which lifecycle applies: EMAIL steps get the full dispatch pipeline; LINKEDIN and
    # CALL are draft-only (pending/generating/ready/failed/approved) — subject is unused
    # for CALL, and body holds the LinkedIn message / call script respectively.
    channel: Mapped[DraftChannel] = mapped_column(
        Enum(DraftChannel, name="draft_channel"), default=DraftChannel.EMAIL, nullable=False
    )
    step_index: Mapped[int] = mapped_column(Integer, default=STEP_INITIAL, nullable=False)

    status: Mapped[DraftStatus] = mapped_column(
        Enum(DraftStatus, name="draft_status"), default=DraftStatus.PENDING, nullable=False
    )
    subject: Mapped[str | None] = mapped_column(String(512), nullable=True)
    body: Mapped[str | None] = mapped_column(Text, nullable=True)
    personalization_notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    booking_link: Mapped[str | None] = mapped_column(String(2048), nullable=True)
    ai_model: Mapped[str | None] = mapped_column(String(100), nullable=True)
    ai_cached: Mapped[bool] = mapped_column(default=False, nullable=False)
    error_message: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    # Superseded versions ({subject, body, refined_with}), oldest first — the "previous
    # drafts in this thread" context for regenerate/refine.
    history: Mapped[list] = mapped_column(JSONB, default=list, nullable=False)

    # Last "send test" target + timestamp, used both to remember the address the user
    # tested with and as a cooldown guard against duplicate double-click sends.
    last_test_email: Mapped[str | None] = mapped_column(String(320), nullable=True)
    last_test_sent_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Counts every refine/regenerate call against this draft (Regenerate, Shorter, More
    # Technical, More Executive, More Friendly, Personalize Further all share this one
    # pool) — capped at REFINE_LIMIT per draft. Each email step (initial, follow-ups,
    # LinkedIn, call) will get its own row and therefore its own independent counter
    # once those steps become real drafts; today only the initial email exists.
    refine_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    # When the REAL send (not a test send) went out — set once, when status flips to
    # SENT. Displayed in place of the action buttons, which disappear once sent.
    sent_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Dispatch scheduling (scheduling_service). scheduled_at is the claimed UTC slot;
    # scheduled_by_user_id denormalizes the owner so the partial unique index
    # ux_email_drafts_user_slot can enforce one-dispatch-per-slot at the DB level.
    scheduled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    scheduled_by_user_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    # Dispatch attempts so far (transient failures auto-retry up to a cap).
    attempt_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    # RFC 5322 Message-ID stamped BEFORE the SMTP send, so an interrupted dispatch
    # can be verified against the mailbox's Sent folder.
    message_id: Mapped[str | None] = mapped_column(String(512), nullable=True)

    lead = relationship("Lead", back_populates="email_drafts")
    dispatch_logs = relationship("DispatchLog", back_populates="draft", cascade="all, delete-orphan")


class DispatchLog(Base, TimestampMixin):
    """Audit trail: one row per dispatch attempt (scheduled or manual), successful or
    not. Answers "why did this email go out at 9:04, not 9:00?" and makes every
    incident reconstructable."""

    __tablename__ = "dispatch_logs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    draft_id: Mapped[int] = mapped_column(
        ForeignKey("email_drafts.id", ondelete="CASCADE"), nullable=False, index=True
    )
    attempt: Mapped[int] = mapped_column(Integer, default=1, nullable=False)
    scheduled_for: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    # sent / retry_scheduled / failed / skipped_paused / skipped_no_mailbox /
    # skipped_no_email / stuck / cancelled / manual_sent / manual_deferred ...
    outcome: Mapped[str] = mapped_column(String(50), nullable=False)
    detail: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    message_id: Mapped[str | None] = mapped_column(String(512), nullable=True)

    draft = relationship("EmailDraft", back_populates="dispatch_logs")
